/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defenceSystem.gui;

import defenceSystem.model.SuperDefence;
import defenceSystem.model.Observer;
import java.util.ArrayList;

public class MainControllerGUI extends SuperDefence {
    private Observer sbj;
    private ArrayList<String> list;

/**
 *
 * @author User
 */
 public MainControllerGUI(boolean res) {
        initComponents();
        setVisible(res);
        list = new ArrayList<>();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectDefenceComboBox = new javax.swing.JComboBox<>();
        collectInfoButton = new javax.swing.JButton();
        soldierCountLabel = new javax.swing.JLabel();
        fuelAmountLabel = new javax.swing.JLabel();
        ammoCountLabel = new javax.swing.JLabel();
        SoldierCountTextField = new javax.swing.JTextField();
        fuelAmountTextField = new javax.swing.JTextField();
        ammoCountTextField = new javax.swing.JTextField();
        positionSlider = new javax.swing.JSlider();
        positionLabel = new javax.swing.JLabel();
        helicopterScrollPane = new javax.swing.JScrollPane();
        helicopterTextArea = new javax.swing.JTextArea();
        tankScrollPane = new javax.swing.JScrollPane();
        tankTextArea = new javax.swing.JTextArea();
        submarineScrollPane = new javax.swing.JScrollPane();
        submarineTextArea = new javax.swing.JTextArea();
        sendpvtCheckBox = new javax.swing.JCheckBox();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectDefenceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helicopter", "Tank", "Submarine" }));
        selectDefenceComboBox.setAutoscrolls(true);
        selectDefenceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDefenceComboBoxActionPerformed(evt);
            }
        });

        collectInfoButton.setText("Collect Informations");
        collectInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectInfoButtonActionPerformed(evt);
            }
        });

        soldierCountLabel.setText("Soldier Count");

        fuelAmountLabel.setText("Fuel Amount");

        ammoCountLabel.setText("Ammo Amount");

        SoldierCountTextField.setEditable(false);
        SoldierCountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldierCountTextFieldActionPerformed(evt);
            }
        });

        fuelAmountTextField.setEditable(false);

        ammoCountTextField.setEditable(false);

        positionSlider.setMajorTickSpacing(10);
        positionSlider.setPaintLabels(true);
        positionSlider.setPaintTicks(true);
        positionSlider.setSnapToTicks(true);
        positionSlider.setOpaque(true);
        positionSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                positionSliderStateChanged(evt);
            }
        });

        positionLabel.setText("Position");

        helicopterTextArea.setColumns(20);
        helicopterTextArea.setRows(5);
        helicopterScrollPane.setViewportView(helicopterTextArea);

        tankTextArea.setColumns(20);
        tankTextArea.setRows(5);
        tankScrollPane.setViewportView(tankTextArea);

        submarineTextArea.setColumns(20);
        submarineTextArea.setRows(5);
        submarineScrollPane.setViewportView(submarineTextArea);

        sendpvtCheckBox.setText("Send Private");
        sendpvtCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendpvtCheckBoxActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submarineScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tankScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(selectDefenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(collectInfoButton))
                        .addComponent(positionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ammoCountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(fuelAmountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(soldierCountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SoldierCountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(fuelAmountTextField)
                                        .addComponent(ammoCountTextField)))
                                .addComponent(positionLabel))
                            .addGap(78, 78, 78)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(sendpvtCheckBox)
                                    .addGap(46, 46, 46)
                                    .addComponent(sendButton))
                                .addComponent(helicopterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDefenceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collectInfoButton))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soldierCountLabel)
                            .addComponent(SoldierCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fuelAmountLabel)
                            .addComponent(fuelAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ammoCountLabel)
                            .addComponent(ammoCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(helicopterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(positionLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendpvtCheckBox)
                            .addComponent(sendButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tankScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submarineScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void setSubject(Observer sbj){
        this.sbj=sbj;
    }
    
     public void setMsg(String str){
        list.add(str);
        StringBuilder sb = new StringBuilder();
        for (String item : list) {
            sb.append(item).append("\n");
        }
        submarineTextArea.setText(sb.toString());
   }
    
    
    private void selectDefenceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDefenceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDefenceComboBoxActionPerformed

    private void SoldierCountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldierCountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoldierCountTextFieldActionPerformed

    private void collectInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collectInfoButtonActionPerformed

    private void sendpvtCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendpvtCheckBoxActionPerformed
        // TODO add your handling code here:
        sbj.methodClear(sendpvtCheckBox.isSelected());
    }//GEN-LAST:event_sendpvtCheckBoxActionPerformed

    private void positionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_positionSliderStateChanged
        // TODO add your handling code here:
        sbj.methodPosition(positionSlider.getValue());
    }//GEN-LAST:event_positionSliderStateChanged

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        sbj.methodMsg(helicopterTextArea.getText());
        helicopterTextArea.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainControllerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainController().setVisible(res);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SoldierCountTextField;
    private javax.swing.JLabel ammoCountLabel;
    private javax.swing.JTextField ammoCountTextField;
    private javax.swing.JButton collectInfoButton;
    private javax.swing.JLabel fuelAmountLabel;
    private javax.swing.JTextField fuelAmountTextField;
    private javax.swing.JScrollPane helicopterScrollPane;
    private javax.swing.JTextArea helicopterTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JSlider positionSlider;
    private javax.swing.JComboBox<String> selectDefenceComboBox;
    private javax.swing.JButton sendButton;
    private javax.swing.JCheckBox sendpvtCheckBox;
    private javax.swing.JLabel soldierCountLabel;
    private javax.swing.JScrollPane submarineScrollPane;
    private javax.swing.JTextArea submarineTextArea;
    private javax.swing.JScrollPane tankScrollPane;
    private javax.swing.JTextArea tankTextArea;
    // End of variables declaration//GEN-END:variables


}
